name: Android CI
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System and Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk git libssl-dev libffi-dev zlib1g-dev libncurses5-dev ccache unzip ant
        python -m pip install --upgrade pip
        pip install 'buildozer==1.5.0' 'cython==0.29.36' 'pyjnius==1.6.1'

    - name: Pre-accept Android licenses
      run: |
        mkdir -p $HOME/.android/
        touch $HOME/.android/repositories.cfg
        mkdir -p $HOME/.android/licenses/
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/.android/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/.android/licenses/android-sdk-license

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug.apk
        path: bin/*.apk
