name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: |
            sed -i 's/from long import Py_jlong/from long long import Py_jlong/' /usr/local/lib/python3.11/site-packages/jnius/jnius_export_class.h
            buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
