# גרסת תיקון מלאה
rm -f ~/Myapp/buildozer.spec
cat > ~/Myapp/buildozer.spec << 'EOF'
[buildozer]
log_level = 2

[app]
title = MyApp
package.name = myapp
package.domain = com.example
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3,kivy==2.1.0,pyjnius==1.6.1
orientation = portrait
fullscreen = 0
android.api = 33
android.minapi = 21
android.sdk_path = /data/data/com.termux/files/home/android_environment/sdk
android.ndk_path = /data/data/com.termux/files/home/android_environment/ndk-r25b
android.sdk_build_tools = 34.0.0
android.accept_sdk_license = True
android.archs = arm64-v8a,armeabi-v7a
p4a.branch = master
android.p4a_dir = /data/data/com.termux/files/home/.buildozer/android/platform/python-for-android
android.allow_backup = true
android.allow_storage_access = true
android.enable_androidx = true
EOF

# הרצה עם הגדרות אופטימליות
cd ~/Myapp
CFLAGS="-I/data/data/com.termux/files/usr/include" \
LDFLAGS="-L/data/data/com.termux/files/usr/lib" \
buildozer -v android debug
