name: Android CI
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Build Environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev unzip
        python3 -m pip install --upgrade pip wheel setuptools
        pip3 install buildozer cython==0.29.36 pyjnius==1.6.1
    
    - name: Create Android environment
      run: |
        mkdir -p "android_environment/sdk"
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q -o cmdline-tools.zip -d "android_environment/sdk"
        mv "android_environment/sdk/cmdline-tools" "android_environment/sdk/tools"
        rm cmdline-tools.zip
        yes | android_environment/sdk/tools/bin/sdkmanager --sdk_root="android_environment/sdk" --licenses
        android_environment/sdk/tools/bin/sdkmanager --sdk_root="android_environment/sdk" "platforms;android-33" "build-tools;34.0.0" "platform-tools"
        
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O android-ndk.zip
        unzip -q -o android-ndk.zip -d "android_environment"
        mv "android_environment/android-ndk-r25b" "android_environment/ndk-r25b"
        rm android-ndk.zip
    
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << EOL
        [buildozer]
        log_level = 2
        
        [app]
        title = MyApp
        package.name = myapp
        package.domain = com.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0.0
        requirements = python3,kivy==2.1.0
        orientation = portrait
        android.api = 33
        android.minapi = 21
        android.sdk_build_tools = 34.0.0
        android.accept_sdk_license = True
        android.sdk_path = ./android_environment/sdk
        android.ndk_path = ./android_environment/ndk-r25b
        android.skip_update = True
        EOL
        
        cat buildozer.spec
    
    - name: Build APK
      run: |
        buildozer -v android debug
        
        echo "=== APK search results ==="
        find . -name "*.apk" -print
        
        mkdir -p apk_output
        find . -name "*.apk" -exec cp {} apk_output/ \;
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug
        path: apk_output/*.apk






