name: Build APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: |
            sed -i "s/requirements = .*/requirements = python==3.9,kivy/" buildozer.spec
            buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: '*.apk'
