name: Android CI with Official Kivy Docker
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    # This is the official, maintained image for Kivy Android builds
    container:
      image: kivy/buildozer-action:master

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the APK
      # The container has everything pre-installed. We just run the build.
      run: buildozer -v android debug

    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug.apk
        # The official container guarantees the output path is bin/
        path: bin/*.apk
