name: Android CI
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    container:
      image: kivy/kivy-android:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create complete buildozer.spec
      run: |
        cat > buildozer.spec << 'SPEC'
        [buildozer]
        warn_on_root = 0
        log_level = 2
        [app]
        title = MyApp
        package.name = myapp
        package.domain = com.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 1.0.0
        requirements = python3,kivy
        orientation = portrait
        fullscreen = 0
        android.api = 33
        android.minapi = 21
        android.sdk_path = /home/kivy/.buildozer/android/platform/android-sdk
        android.ndk_path = /home/kivy/.buildozer/android/platform/android-ndk-r25b
        android.sdk_build_tools = 34.0.0
        android.permissions = INTERNET
        android.arch = armeabi-v7a
        p4a.branch = master
        SPEC
    - name: Pre-accept Android licenses
      run: |
        mkdir -p /home/kivy/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > /home/kivy/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> /home/kivy/.android/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > /home/kivy/.android/licenses/android-sdk-preview-license
    - name: Build APK with Buildozer
      run: |
        pip install setuptools==65.5.0
        buildozer -v android debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug.apk
        path: bin/*.apk
