name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    
    - name: Grant Execute Permissions to build-tools
      run: |
        chmod +x $ANDROID_HOME/build-tools/34.0.0/aapt
        chmod +x $ANDROID_HOME/build-tools/34.0.0/aapt2
        chmod +x $ANDROID_HOME/build-tools/34.0.0/zipalign
        chmod +x $ANDROID_HOME/build-tools/34.0.0/apksigner

    - name: Build with Buildozer
      run: |
        buildozer -v android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk



