name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk  # מיקום ה-SDK המובנה של GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk git libssl-dev libffi-dev zlib1g-dev libncurses5-dev ccache

    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36 pyjnius==1.6.1

    - name: Configure and build APK with Buildozer
      run: |
        # יצירת קובץ buildozer.spec חדש
        buildozer init

        # עדכון הגדרות בסיסיות
        sed -i "s/^title = .*/title = MyApp/" buildozer.spec
        sed -i "s/^package.name = .*/package.name = myapp/" buildozer.spec
        sed -i "s/^package.domain = .*/package.domain = com.example/" buildozer.spec

        # הגדרת ה-SDK המובנה והגרסאות המדויקות
        echo "android.sdk_path = $ANDROID_HOME" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.sdk_build_tools = 34.0.0" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.ndk = 25.2.9519653" >> buildozer.spec

        # הרצת הבנייה עם דיבוג מלא
        buildozer -v android debug --log-level=2

    - name: Move APK to bin directory
      run: |
        mkdir -p bin
        mv *.apk bin/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-debug-apk
        path: bin/*.apk
