name: Build APK

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk zlib1g-dev
          
      - name: Install Buildozer
        run: pip install buildozer
      
      - name: Create buildozer.spec
        run: |
          echo "[app]" > buildozer.spec
          echo "title = MyApp" >> buildozer.spec
          echo "package.name = myapp" >> buildozer.spec
          echo "package.domain = org.test" >> buildozer.spec
          echo "source.dir = ." >> buildozer.spec
          echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
          echo "version = 1.0" >> buildozer.spec
          echo "requirements = python3,kivy" >> buildozer.spec
          echo "android.sdk = 33" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec
          echo "[buildozer]" >> buildozer.spec
          echo "log_level = 2" >> buildozer.spec
      
      - name: Fix jnius error
        run: |
          find ~/.buildozer -name jnius_export_class.h -exec sed -i 's/from long import Py_jlong/from long long import Py_jlong/' {} \;
          
      - name: Build APK
        run: buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk


